### ISSUE TITLE
Remove stops that are assigned after school

### ISSUE THREAD

**Issue by simonkassel** [azavea/bus-plan#68]
I'm still getting some cases in which the solver will assign a stop after a school. I know that @jamesmcclain  fixed this at some point but I think we may have not merged those changes for some workflow reason. We should figure out how to re-implement this.

**Comment by jamesmcclain** [comment]
No, it was never fixed.  Recall our earlier discussion when I mis-remembered that it had been fixed, but then I recalled https://github.com/azavea/bus-plan/issues/25 which was motivated by that issue but never addressed.  The stops after schools should always be empty so they can be safely ignored.
